## Lab 2, Raul Castellanos 20180052

In [6]:
import numpy as np

## Problema 1

In [48]:
M = np.array([
    [1,1,0,0,0,0,1],
    [0,1,1,0,0,1,0],
    [0,0,1,1,0,0,0],
    [0,0,0,1,1,0,1],
    [1,0,0,0,0,1,1],
    [0,0,0,0,1,1,1],
    [1,1,1,0,0,0,1]
])

M1 = np.array([
    [1,1,0,0,0,1,1],
    [1,1,1,0,1,0,0],
    [0,1,1,1,1,0,0],
    [0,0,1,1,0,0,1],
    [0,1,1,0,1,1,1],
    [1,0,0,0,1,1,1],
    [1,0,0,1,1,1,1]
])

M2 = np.array([
    [1,1,0,0,0,0,0],
    [1,1,0,0,0,0,0],
    [0,0,1,1,0,0,0],
    [0,0,1,1,0,0,0],
    [0,0,0,0,1,1,1],
    [0,0,0,0,1,1,1],
    [0,0,0,0,1,1,1]
])

print(M)
print('\n')
print(M1)
print('\n')
print(M2)

[[1 1 0 0 0 0 1]
 [0 1 1 0 0 1 0]
 [0 0 1 1 0 0 0]
 [0 0 0 1 1 0 1]
 [1 0 0 0 0 1 1]
 [0 0 0 0 1 1 1]
 [1 1 1 0 0 0 1]]


[[1 1 0 0 0 1 1]
 [1 1 1 0 1 0 0]
 [0 1 1 1 1 0 0]
 [0 0 1 1 0 0 1]
 [0 1 1 0 1 1 1]
 [1 0 0 0 1 1 1]
 [1 0 0 1 1 1 1]]


[[1 1 0 0 0 0 0]
 [1 1 0 0 0 0 0]
 [0 0 1 1 0 0 0]
 [0 0 1 1 0 0 0]
 [0 0 0 0 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 1 1 1]]


In [62]:
def R_Reflexiva(m):
    if (np.diagonal(m).sum() == m.shape[0]):
        print('La relación R es reflexiva')
    else: print('La relación R no es reflexiva')
        
print('Para M')
R_Reflexiva(M)
print('\n')

print('Para M1')
R_Reflexiva(M1)
print('\n')

print('Para M2')
R_Reflexiva(M2)
print('\n')


def R_Simetrica(m):
    if ((m==np.transpose(m)).all()):
        print('La relación R es simétrica')
    else: print('La relación R no es simétrica')
        
print('Para M')
R_Simetrica(M)
print('\n')

print('Para M1')
R_Simetrica(M1)
print('\n')

print('Para M2')
R_Simetrica(M2)
print('\n')


def R_Transitiva(m):
    M = m.dot(m)
    M[M>=1] = 1
    if ((m==M).all()):
        print('La relación R es transitiva')
    else: print('La relación R no es transitiva')
        
print('Para M')
R_Transitiva(M)
print('\n')

print('Para M1')
R_Transitiva(M1)
print('\n')

print('Para M2')
R_Transitiva(M2)
print('\n')


Para M
La relación R no es reflexiva


Para M1
La relación R es reflexiva


Para M2
La relación R es reflexiva


Para M
La relación R no es simétrica


Para M1
La relación R es simétrica


Para M2
La relación R es simétrica


Para M
La relación R no es transitiva


Para M1
La relación R no es transitiva


Para M2
La relación R es transitiva




## Problema 2

In [11]:
A = np.arange(5,9).reshape(2,2)
A

array([[5, 6],
       [7, 8]])

In [12]:
B = np.arange(-7,-1).reshape(2,3)
B

array([[-7, -6, -5],
       [-4, -3, -2]])

In [13]:
C = np.arange(4,14,3).reshape(2,2)
C

array([[ 4,  7],
       [10, 13]])

In [14]:
D = np.eye(2)
D

array([[1., 0.],
       [0., 1.]])

In [18]:
E = np.zeros(6).reshape(2,3)
E

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# Arriba 
H1 = np.hstack([A,D,E])

# Abajo
H2 = np.hstack([D,C,B])

H = np.vstack([H1,H2])
H

array([[ 5.,  6.,  1.,  0.,  0.,  0.,  0.],
       [ 7.,  8.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  4.,  7., -7., -6., -5.],
       [ 0.,  1., 10., 13., -4., -3., -2.]])

## Problema 3

In [28]:
A3 = np.arange(0,24).reshape(4,6)
A3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [32]:
def g90(m): 
    x = np.transpose(m)
    print('Rota 90 grados \n', np.flip(x,0), '\n')
    
g90(A3)

def g180(m): 
    x = np.flip(m)
    print('Rota 180 grados \n', x, '\n')
g180(A3)

def g270(m): 
    x = np.flip(m,0)
    print('Rota 270 grados \n', np.transpose(x), '\n')
g270(A3)

Rota 90 grados 
 [[ 5 11 17 23]
 [ 4 10 16 22]
 [ 3  9 15 21]
 [ 2  8 14 20]
 [ 1  7 13 19]
 [ 0  6 12 18]] 

Rota 180 grados 
 [[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]] 

Rota 270 grados 
 [[18 12  6  0]
 [19 13  7  1]
 [20 14  8  2]
 [21 15  9  3]
 [22 16 10  4]
 [23 17 11  5]] 



In [36]:
# Al reves 
def g90_2(m): 
    x = np.transpose(m)
    print('Rota 90 grados contra reloj \n', np.flip(x,1), '\n')
    
g90_2(A3)

def g180_2(m): 
    x = np.flip(m)
    print('Rota 180 grados contra reloj \n', x, '\n')
g180_2(A3)

def g270_2(m):
    x = np.transpose(m)
    print('Rota 270 grados contra reloj \n', np.flip(x,0), '\n')
g270_2(A3)

Rota 90 grados contra reloj 
 [[18 12  6  0]
 [19 13  7  1]
 [20 14  8  2]
 [21 15  9  3]
 [22 16 10  4]
 [23 17 11  5]] 

Rota 180 grados contra reloj 
 [[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]] 

Rota 270 grados contra reloj 
 [[ 5 11 17 23]
 [ 4 10 16 22]
 [ 3  9 15 21]
 [ 2  8 14 20]
 [ 1  7 13 19]
 [ 0  6 12 18]] 



## Problema 4

### 2x + 1a = 4
### x + a = 3
### -x + 2a = 3 
### 2y + b = 3
### y + b = 2
### -y + 2b = 1
### 2z + c = 6
### z + c = 4
### -z + 2c = 2
### 2t + d = -3
### t + d = -1
### -t + 2d = 4

## Estructura [ x, y, z, a, b , c, d, t]

In [47]:
X = np.array([
[2,0,0,1,0,0,0,0],
[1,0,0,1,0,0,0,0],
[-1,0,0,2,0,0,0,0],
[0,2,0,0,1,0,0,0],
[0,1,0,0,1,0,0,0],
[0,-1,0,0,2,0,0,0],
[0,0,2,0,0,1,0,0],
[0,0,1,0,0,1,0,0],
[0,0,-1,0,0,2,0,0],
[0,0,0,0,0,0,1,2],
[0,0,0,0,0,0,1,1],
[0,0,0,0,0,0,2,-1]
])

R = np.array([
    [4],
    [3],
    [3],
    [3],
    [2],
    [1],
    [6],
    [4],
    [2],
    [-3],
    [-1],
    [4]
])

print(X)
print('\n')
print(R)

print('\n')

# Solucion 1 
Solucion_NoCuadrada = np.linalg.lstsq(X, R)
Solucion_NoCuadrada[0]

# Solucion 2
Solucion_NoCuadrada2 = np.linalg.pinv(X).dot(R)
Solucion_NoCuadrada2

[[ 2  0  0  1  0  0  0  0]
 [ 1  0  0  1  0  0  0  0]
 [-1  0  0  2  0  0  0  0]
 [ 0  2  0  0  1  0  0  0]
 [ 0  1  0  0  1  0  0  0]
 [ 0 -1  0  0  2  0  0  0]
 [ 0  0  2  0  0  1  0  0]
 [ 0  0  1  0  0  1  0  0]
 [ 0  0 -1  0  0  2  0  0]
 [ 0  0  0  0  0  0  1  2]
 [ 0  0  0  0  0  0  1  1]
 [ 0  0  0  0  0  0  2 -1]]


[[ 4]
 [ 3]
 [ 3]
 [ 3]
 [ 2]
 [ 1]
 [ 6]
 [ 4]
 [ 2]
 [-3]
 [-1]
 [ 4]]




<ipython-input-47-c8264d94e594>:38: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  Solucion_NoCuadrada = np.linalg.lstsq(X, R)


array([[ 1.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 1.],
       [ 2.],
       [ 1.],
       [-2.]])